---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: mitchty/alpine-ghc
    tag: latest
inputs:
  - name: quorum-pipeline-git
outputs:
  - name: build-constellation-output
params:
  OUTPUT_DIR: build-constellation-output
run:
  path: quorum-pipeline-git/tasks/build-constellation/task
