#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

true ${CONSTELLATION_SRC_DIR:?"!"}
true ${OUTPUT_DIR:?"!"}

# for leveldb
echo http://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories

apk update
apk upgrade
apk add musl-dev gmp-dev zlib-dev pcre-dev llvm clang \
        leveldb-dev linux-headers \
        alpine-sdk git ca-certificates gmp-dev zlib-dev libsodium-dev db-dev ncurses-dev ncurses-static \
;

pushd $CONSTELLATION_SRC_DIR
  stack install \
    --system-ghc \
    --split-objs \
    --ghc-options="-fPIC -fllvm" \
  ;
popd

cp /root/.local/bin/* \
  $OUTPUT_DIR/
