groups:
- name: quorum-deploy
  jobs:
  - quorum-build-and-deploy
resources:
- name: quorum-git
  type: git
  source:
    branch: master
    uri: https://github.com/jpmorganchase/quorum.git
- name: quorum-pipeline-git
  type: git
  source:
    branch: master
    uri: {{pipeline_repo_url}}
- name: cf-push
  type: cf
  source:
    api: {{cf_api_url}}
    username: {{cf_username}}
    password: {{cf_password}}
    organization: {{cf_org}}
    space: {{cf_space}}
    skip_cert_check: true
jobs:
- name: quorum-build-and-deploy
  plan:
  - get: quorum-git
    #trigger: true
  - get: quorum-pipeline-git
  - task: build
    file: quorum-pipeline-git/tasks/build-task.yml
  - put: cf-push
    params:
      manifest: build-output/manifest.yml
