groups:
- name: quorum-deploy
  jobs:
  - quorum-build-and-deploy
resources:
- name: quorum-git
  type: git
  source:
    branch: master
    uri: https://github.com/jpmorganchase/quorum.git
- name: constellation-git
  type: git
  source:
    branch: master
    uri: https://github.com/jpmorganchase/constellation.git
- name: quorum-examples-git
  type: git
  source:
    branch: master
    uri: https://github.com/jpmorganchase/quorum-examples.git
- name: quorum-pipeline-git
  type: git
  source:
    branch: master
    uri: {{pipeline_repo_url}}
- name: cache
  type: git
  source:
    branch: cache
    uri: {{state_repo_url}}
    private_key: !!binary {{state_repo_private_key}}
- name: cf-push
  type: cf
  source:
    api: {{cf_api_url}}
    username: {{cf_username}}
    password: {{cf_password}}
    organization: {{cf_org}}
    space: {{cf_space}}
    skip_cert_check: true
jobs:
- name: quorum-build-and-deploy
  plan:
  - aggregate:
    - get: quorum-git
      #trigger: true
    - get: constellation-git
    - get: quorum-pipeline-git
    - get: quorum-examples-git
    - get: cache
  - task: cache-prep
    file: quorum-pipeline-git/tasks/cache-task.yml
    input_mapping: { cache-input: cache, cache-output: cache }
  - aggregate:
    - task: build-quorum
      file: quorum-pipeline-git/tasks/build-quorum-task.yml
    - task: build-constellation
      file: quorum-pipeline-git/tasks/build-constellation-task.yml
      input_mapping: { cache-input: cache, cache-output: cache }
  - task: build-nodes
    file: quorum-pipeline-git/tasks/build-nodes-task.yml
  - aggregate:
    - put: cf-push
      params:
        manifest: build-output/manifest.yml
        path: build-output/
    - put: cache
