#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

SRC_DIR=${SRC_DIR:?"!"}
EXAMPLES_DIR=${EXAMPLES_DIR:?"!"}
PIPELINE_DIR=${PIPELINE_DIR:?"!"}
OUTPUT_DIR=${OUTPUT_DIR:?"!"}

pushd $SRC_DIR
  make all
popd

pushd $EXAMPLES_DIR/examples/7nodes/
  ./init.sh
popd

cp $SRC_DIR/build/bin/geth \
  $OUTPUT_DIR/geth
cp $SRC_DIR/build/bin/bootnode \
  $OUTPUT_DIR/bootnode
cp $PIPELINE_DIR/manifest.yml \
  $OUTPUT_DIR/manifest.yml
cp -r $EXAMPLES_DIR/examples/7nodes/* \
  $OUTPUT_DIR/
