---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7-wheezy
inputs:
  - name: quorum-git
  - name: quorum-pipeline-git
outputs:
  - name: build-quorum-output
params:
  QUORUM_SRC_DIR: quorum-git
  OUTPUT_DIR: build-quorum-output
run:
  path: quorum-pipeline-git/tasks/build-quorum-task
