#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

QUORUM_SRC_DIR=${QUORUM_SRC_DIR:?"!"}
CONSTELLATION_SRC_DIR=${CONSTELLATION_SRC_DIR:?"!"}
EXAMPLES_DIR=${EXAMPLES_DIR:?"!"}
PIPELINE_DIR=${PIPELINE_DIR:?"!"}
OUTPUT_DIR=${OUTPUT_DIR:?"!"}

pushd $QUORUM_SRC_DIR
  make all
popd

sudo apt-get install haskell-stack
pushd $CONSTELLATION_SRC_DIR
  stack install
popd


mkdir $OUTPUT_DIR/bin
cp $QUORUM_SRC_DIR/build/bin/geth \
  $OUTPUT_DIR/bin/geth
cp $QUORUM_SRC_DIR/build/bin/bootnode \
  $OUTPUT_DIR/bin/bootnode
cp $QUORUM_SRC_DIR/build/bin/constellation-node \
  $CONSTELLATION_SRC_DIR/bin/constellation-node

pushd $OUTPUT_DIR
  export PATH=$PATH:`pwd`/bin
popd

pushd $EXAMPLES_DIR/examples/7nodes/
  ./init.sh
popd

cp -r $EXAMPLES_DIR/examples/7nodes/* \
  $OUTPUT_DIR/

cp $PIPELINE_DIR/min-start.sh \
  $OUTPUT_DIR/min-start.sh
cp $PIPELINE_DIR/manifest.yml \
  $OUTPUT_DIR/manifest.yml
