#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

_=${OUTPUT_DIR:?"!"}

apt-get update
apt-get install -y curl unzip

curl -L https://github.com/jpmorganchase/constellation/releases/download/v0.0.1-alpha/ubuntu1604.zip \
  > constellation.zip
 
unzip -j constellation.zip
chmod +x constellation-node constellation-enclave-keygen 

cp constellation-node constellation-enclave-keygen \
  $OUTPUT_DIR/

