#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

true ${SERVICE_NAME:?"!"}
true ${CF_API:?"!"}
true ${CF_USERNAME:?"!"}
true ${CF_PASSWORD:?"!"}
true ${CF_ORGANIZATION:?"!"}
true ${CF_SPACE:?"!"}

curl -L "https://cli.run.pivotal.io/stable?release=debian64&version=6.26.0&source=github-rel" > cfcli.deb
dpkg -i cfcli.deb

cf login -a "$CF_API" -u "$CF_USERNAME" -p "$CF_PASSWORD" -o "$CF_ORGANIZATION" -s "$CF_SPACE"
cat > credentials.json <<EOF
{
  "CF_API": "$CF_API",
  "CF_USERNAME": "$CF_USERNAME",
  "CF_PASSWORD": "$CF_PASSWORD",
  "CF_ORGANIZATION": "$CF_ORGANIZATION",
  "CF_SPACE": "$CF_SPACE"
}
EOF

if cf service $SERVICE_NAME; then
  cf update-user-provided-service $SERVICE_NAME -p credentials.json
else
  cf create-user-provided-service $SERVICE_NAME -p credentials.json
fi
