---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: buildpack-deps
    tag: jessie-curl
inputs:
  - name: artifacts
  - name: examples
  - name: pipelines
outputs:
  - name: configs
run:
  path: pipelines/tasks/init-config/task
