resources:
- name: quorum-pipeline-git
  type: git
  source:
    branch: wip/external-repo
    uri: {{pipeline_repo_url}}
- name: quorum-pcf-7nodes
  type: git
  source:
    branch: master
    uri: https://github.com/micahyoung/quorum-pcf-7nodes.git
- name: quorum-git
  type: git
  source:
    branch: master
    uri: https://github.com/jpmorganchase/quorum.git
- name: constellation-git
  type: git
  source:
    branch: master
    uri: https://github.com/jpmorganchase/constellation.git
- name: quorum-examples-git
  type: git
  source:
    branch: master
    uri: https://github.com/jpmorganchase/quorum-examples.git
- name: quorum-bin-release
  type: github-release
  source:
    user: {{github_release_owner}}
    repository: {{github_release_repo}}
    access_token: {{github_release_token}}
    pre_release: true
- name: cf-push
  type: cf
  source:
    api: {{cf_api_url}}
    username: {{cf_username}}
    password: {{cf_password}}
    organization: {{cf_org}}
    space: {{cf_space}}
jobs:
- name: quorum-build
  build_logs_to_retain: 10
  plan:
  - aggregate:
    - get: quorum-git
      trigger: true
    - get: constellation-git
    - get: quorum-pipeline-git
  - aggregate:
    - task: build-quorum
      file: quorum-pipeline-git/tasks/build-quorum/task.yml
    - task: build-constellation
      file: quorum-pipeline-git/tasks/build-constellation/task.yml
    - task: build-solidity
      file: quorum-pipeline-git/tasks/build-solidity/task.yml
      input_mapping:
        pipelines: quorum-pipeline-git
      output_mapping:
        solidity-bin: build-solidity-output
  - put: quorum-bin-release
    params:
      name: quorum-pipeline-git/versions/QUORUM_BIN_VERSION
      tag: quorum-pipeline-git/versions/QUORUM_BIN_VERSION
      globs:
        - build-quorum-output/*
        - build-constellation-output/*
        - build-solidity-output/*
- name: init-nodes
  build_logs_to_retain: 10
  plan:
  - aggregate:
    - get: quorum-pipeline-git
  - task: init-nodes
    file: quorum-pipeline-git/tasks/init-nodes/task.yml
    input_mapping:
      pipelines: quorum-pipeline-git
    params:
- name: deploy-bootnode
  build_logs_to_retain: 10
  plan:
  - aggregate:
    - get: quorum-pcf-7nodes
      trigger: true
    - get: quorum-bin-release
      globs: ['*']
      passed: [quorum-build]
      trigger: true
    - get: quorum-examples-git
    - get: quorum-pipeline-git
  - task: assemble-node
    file: quorum-pipeline-git/tasks/assemble-node/task.yml
    input_mapping:
      artifacts: quorum-bin-release
      examples: quorum-examples-git
      run-scripts: quorum-pcf-7nodes
      pipelines: quorum-pipeline-git
    output_mapping:
      deploy: deploy
  - put: cf-push
    manifest: quorum-pipeline-git/manifests/bootnode-manifest.yml
    path: deploy/
    current_app_name: bootnode
- name: deploy-node1
  build_logs_to_retain: 10
  plan:
  - aggregate:
    - get: quorum-pcf-7nodes
      passed: [deploy-bootnode]
      trigger: true
    - get: quorum-bin-release
      globs: ['*']
      passed: [deploy-bootnode]
    - get: quorum-examples-git
      passed: [deploy-bootnode]
    - get: quorum-pipeline-git
  - task: assemble-node
    file: quorum-pipeline-git/tasks/assemble-node/task.yml
    input_mapping:
      artifacts: quorum-bin-release
      examples: quorum-examples-git
      run-scripts: quorum-pcf-7nodes
      pipelines: quorum-pipeline-git
    output_mapping:
      deploy: deploy
  - put: cf-push
    manifest: quorum-pipeline-git/manifests/node-1-manifest.yml
    path: deploy/
    current_app_name: node-1
- name: deploy-node2
  build_logs_to_retain: 10
  plan:
  - aggregate:
    - get: quorum-pcf-7nodes
      passed: [deploy-node1]
      trigger: true
    - get: quorum-bin-release
      globs: ['*']
      passed: [deploy-node1]
    - get: quorum-examples-git
      passed: [deploy-node1]
    - get: quorum-pipeline-git
  - task: deploy-node
    file: quorum-pipeline-git/tasks/assemble-node/task.yml
    input_mapping:
      artifacts: quorum-bin-release
      configs: quorum-examples-git
      pipelines: quorum-pipeline-git
    params:
      NODE_NAME: node-2
      MANIFEST_NAME: node2-manifest.yml
      CF_API: {{cf_api_url}}
      CF_USERNAME: {{cf_username}}
      CF_PASSWORD: {{cf_password}}
      CF_ORGANIZATION: {{cf_org}}
      CF_SPACE: {{cf_space}}
- name: deploy-node3
  build_logs_to_retain: 10
  plan:
  - aggregate:
    - get: quorum-pcf-7nodes
      passed: [deploy-node1]
      trigger: true
    - get: quorum-bin-release
      globs: ['*']
      passed: [deploy-node1]
    - get: quorum-examples-git
      passed: [deploy-node1]
    - get: quorum-pipeline-git
  - task: deploy-node
    file: quorum-pipeline-git/tasks/assemble-node/task.yml
    input_mapping:
      artifacts: quorum-bin-release
      configs: quorum-examples-git
      pipelines: quorum-pipeline-git
    params:
      NODE_NAME: node-3
      MANIFEST_NAME: node3-manifest.yml
      CF_API: {{cf_api_url}}
      CF_USERNAME: {{cf_username}}
      CF_PASSWORD: {{cf_password}}
      CF_ORGANIZATION: {{cf_org}}
      CF_SPACE: {{cf_space}}
- name: deploy-node4
  build_logs_to_retain: 10
  plan:
  - aggregate:
    - get: quorum-pcf-7nodes
      passed: [deploy-node1]
      trigger: true
    - get: quorum-bin-release
      globs: ['*']
      passed: [deploy-node1]
    - get: quorum-examples-git
      passed: [deploy-node1]
    - get: quorum-pipeline-git
  - task: deploy-node
    file: quorum-pipeline-git/tasks/assemble-node/task.yml
    input_mapping:
      artifacts: quorum-bin-release
      configs: quorum-examples-git
      pipelines: quorum-pipeline-git
    params:
      NODE_NAME: node-4
      MANIFEST_NAME: node4-manifest.yml
      CF_API: {{cf_api_url}}
      CF_USERNAME: {{cf_username}}
      CF_PASSWORD: {{cf_password}}
      CF_ORGANIZATION: {{cf_org}}
      CF_SPACE: {{cf_space}}
- name: deploy-node5
  build_logs_to_retain: 10
  plan:
  - aggregate:
    - get: quorum-pcf-7nodes
      passed: [deploy-node1]
      trigger: true
    - get: quorum-bin-release
      globs: ['*']
      passed: [deploy-node1]
    - get: quorum-examples-git
      passed: [deploy-node1]
    - get: quorum-pipeline-git
  - task: deploy-node
    file: quorum-pipeline-git/tasks/assemble-node/task.yml
    input_mapping:
      artifacts: quorum-bin-release
      configs: quorum-examples-git
      pipelines: quorum-pipeline-git
    params:
      NODE_NAME: node-5
      MANIFEST_NAME: node5-manifest.yml
      CF_API: {{cf_api_url}}
      CF_USERNAME: {{cf_username}}
      CF_PASSWORD: {{cf_password}}
      CF_ORGANIZATION: {{cf_org}}
      CF_SPACE: {{cf_space}}
- name: deploy-node6
  build_logs_to_retain: 10
  plan:
  - aggregate:
    - get: quorum-pcf-7nodes
      passed: [deploy-node1]
      trigger: true
    - get: quorum-bin-release
      globs: ['*']
      passed: [deploy-node1]
    - get: quorum-examples-git
      passed: [deploy-node1]
    - get: quorum-pipeline-git
  - task: deploy-node
    file: quorum-pipeline-git/tasks/assemble-node/task.yml
    input_mapping:
      artifacts: quorum-bin-release
      configs: quorum-examples-git
      pipelines: quorum-pipeline-git
    params:
      NODE_NAME: node-6
      MANIFEST_NAME: node6-manifest.yml
      CF_API: {{cf_api_url}}
      CF_USERNAME: {{cf_username}}
      CF_PASSWORD: {{cf_password}}
      CF_ORGANIZATION: {{cf_org}}
      CF_SPACE: {{cf_space}}
- name: deploy-node7
  build_logs_to_retain: 10
  plan:
  - aggregate:
    - get: quorum-pcf-7nodes
      passed: [deploy-node1]
      trigger: true
    - get: quorum-bin-release
      globs: ['*']
      passed: [deploy-node1]
    - get: quorum-examples-git
      passed: [deploy-node1]
    - get: quorum-pipeline-git
  - task: deploy-node
    file: quorum-pipeline-git/tasks/assemble-node/task.yml
    input_mapping:
      artifacts: quorum-bin-release
      configs: quorum-examples-git
      pipelines: quorum-pipeline-git
    params:
      NODE_NAME: node-7
      MANIFEST_NAME: node7-manifest.yml
      CF_API: {{cf_api_url}}
      CF_USERNAME: {{cf_username}}
      CF_PASSWORD: {{cf_password}}
      CF_ORGANIZATION: {{cf_org}}
      CF_SPACE: {{cf_space}}
- name: test-node1
  build_logs_to_retain: 10
  plan:
  - aggregate:
    - get: quorum-pcf-7nodes
      trigger: true
      passed:
      - deploy-node2
      - deploy-node3
      - deploy-node4
      - deploy-node5
      - deploy-node6
      - deploy-node7
    - get: quorum-pipeline-git
  - task: test-nodes
    file: quorum-pipeline-git/tasks/test-nodes/task.yml
    input_mapping:
      pipelines: quorum-pipeline-git
    params:
      NODE_NAME: node-1
      CF_API: {{cf_api_url}}
      CF_USERNAME: {{cf_username}}
      CF_PASSWORD: {{cf_password}}
      CF_ORGANIZATION: {{cf_org}}
      CF_SPACE: {{cf_space}}
