#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

true ${CF_API:?"!"}
true ${CF_USERNAME:?"!"}
true ${CF_PASSWORD:?"!"}
true ${CF_ORGANIZATION:?"!"}
true ${CF_SPACE:?"!"}

curl -L "https://cli.run.pivotal.io/stable?release=debian64&version=6.26.0&source=github-rel" > cfcli.deb
dpkg -i cfcli.deb

cf install-plugin \
  https://github.com/cloudfoundry-incubator/cf-networking-release/releases/download/v0.25.0/network-policy-plugin-linux64 \
  -f \
;

cf login -a "$CF_API" -u "$CF_USERNAME" -p "$CF_PASSWORD" -o "$CF_ORGANIZATION" -s "$CF_SPACE"

pushd quorum-pcf
  ./down.sh

  ./up.sh
popd
