#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

true ${NODE_NAME:?"!"}
true ${CF_API:?"!"}
true ${CF_USERNAME:?"!"}
true ${CF_PASSWORD:?"!"}
true ${CF_ORGANIZATION:?"!"}
true ${CF_SPACE:?"!"}

curl -L "https://cli.run.pivotal.io/stable?release=debian64&version=6.26.0&source=github-rel" > cfcli.deb
dpkg -i cfcli.deb

cf login -a "$CF_API" -u "$CF_USERNAME" -p "$CF_PASSWORD" -o "$CF_ORGANIZATION" -s "$CF_SPACE"

TEST_COMMAND='export PATH=$PATH:`pwd`; export LD_LIBRARY_PATH=`pwd`; cd app; export PATH=$PATH:`pwd`/bin; geth --exec "for (i=0; i<10; i++) {loadScript(\"script1.js\")}; var lastTxHash = eth.pendingTransactions[eth.pendingTransactions.length-1].hash; while(eth.pendingTransactions.length > 0) { admin.sleep(1) }; eth.getTransactionReceipt(lastTxHash)" attach qdata/dd1/geth.ipc'
TEST_OUTPUT=`cf ssh $NODE_NAME -c "$TEST_COMMAND"`

echo "$TEST_OUTPUT"

if [[ $TEST_OUTPUT == *"cumulativeGasUsed"* ]]; then
  exit 0
else
  echo "!!!!! Failure: !!!!!"
  exit 1
fi
