#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

true ${NODE_NAME:?"!"}
true ${CF_API:?"!"}
true ${CF_USERNAME:?"!"}
true ${CF_PASSWORD:?"!"}
true ${CF_ORGANIZATION:?"!"}
true ${CF_SPACE:?"!"}

curl -L "https://cli.run.pivotal.io/stable?release=debian64&version=6.26.0&source=github-rel" > cfcli.deb
dpkg -i cfcli.deb

cf login -a "$CF_API" -u "$CF_USERNAME" -p "$CF_PASSWORD" -o "$CF_ORGANIZATION" -s "$CF_SPACE"

TEST_COMMAND='cd app; export PATH=$PATH:`pwd`/bin; geth --exec "loadScript(\"script1.js\"); while(eth.pendingTransactions.length > 0) {admin.sleep(1)}" attach qdata/dd1/geth.ipc'

if cf ssh $NODE_NAME -c "$TEST_COMMAND" | grep "true"; then
  exit 0
else
  echo Failure
  exit 1
fi
