---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas
    tag: cf-cli
inputs:
  - name: pipelines
params:
  NODE_NAME: ~
  CF_API: ~
  CF_USERNAME: ~
  CF_PASSWORD: ~
  CF_ORGANIZATION: ~
  CF_SPACE: ~
run:
  path: pipelines/tasks/test-nodes/task
