#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

true ${SERVICE_NAME:?"!"}
true ${BOOTNODE_APPNAME:?"!"}
true ${OTHER_NODE_APPNAME:?"!"}
true ${CF_API:?"!"}
true ${CF_USERNAME:?"!"}
true ${CF_PASSWORD:?"!"}
true ${CF_ORGANIZATION:?"!"}

curl -L "https://cli.run.pivotal.io/stable?release=debian64&version=6.26.0&source=github-rel" > cfcli.deb
dpkg -i cfcli.deb

cf login -a "$CF_API" -u "$CF_USERNAME" -p "$CF_PASSWORD" -o "$CF_ORGANIZATION" -s "$CF_SPACE"

if grep "started" <(cf app $BOOTNODE_APPNAME); then
  BOOTNODE_IP=$(cf ssh $BOOTNODE_APPNAME -c "hostname --ip-address")
else
  BOOTNODE_IP=""
fi

if grep "started" <(cf app $OTHER_NODE_APPNAME); then
  OTHER_NODE_IP=$(cf ssh $OTHER_NODE_APPNAME -c "hostname --ip-address")
else
  OTHER_NODE_IP=""
fi

echo "BOOTNODE_IP=$BOOTNODE_IP"
echo "OTHER_NODE_IP=$OTHER_NODE_IP"

cat > credentials.json <<EOF
{
  "BOOTNODE_IP": "$BOOTNODE_IP",
  "OTHER_NODE_IP": "$OTHER_NODE_IP"
}
EOF

cf update-user-provided-service $SERVICE_NAME -p credentials.json
