---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: buildpack-deps
    tag: jessie-curl
inputs:
  - name: artifacts
  - name: configs
  - name: pipelines
params:
  NODE_NAME: ~
  MANIFEST_NAME: ~
  CF_API: ~
  CF_USERNAME: ~
  CF_PASSWORD: ~
  CF_ORGANIZATION: ~
  CF_SPACE: ~
run:
  path: pipelines/tasks/deploy-node/task
